# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hwman.grpc.protobufs_compiled import circuits_pb2 as hwman_dot_grpc_dot_protobufs_dot_circuits__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hwman/grpc/protobufs/circuits_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CircuitsStub(object):
    """Service for direct circuit execution on QPU hardware
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCircuit = channel.unary_unary(
                '/hwman.Circuits/RunCircuit',
                request_serializer=hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitRequest.SerializeToString,
                response_deserializer=hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitResponse.FromString,
                _registered_method=True)


class CircuitsServicer(object):
    """Service for direct circuit execution on QPU hardware
    """

    def RunCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CircuitsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCircuit,
                    request_deserializer=hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitRequest.FromString,
                    response_serializer=hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hwman.Circuits', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hwman.Circuits', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Circuits(object):
    """Service for direct circuit execution on QPU hardware
    """

    @staticmethod
    def RunCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hwman.Circuits/RunCircuit',
            hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitRequest.SerializeToString,
            hwman_dot_grpc_dot_protobufs_dot_circuits__pb2.RunCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
