# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hwman/grpc/protobufs/circuits.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'hwman/grpc/protobufs/circuits.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#hwman/grpc/protobufs/circuits.proto\x12\x05hwman\"U\n\x04Gate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x15\n\rtarget_qubits\x18\x02 \x03(\x05\x12\x16\n\x0e\x63ontrol_qubits\x18\x03 \x03(\x05\x12\x0e\n\x06params\x18\x04 \x03(\x01\"K\n\x11RunCircuitRequest\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x1a\n\x05gates\x18\x02 \x03(\x0b\x32\x0b.hwman.Gate\x12\r\n\x05shots\x18\x03 \x01(\x05\"5\n\x11\x44istributionEntry\x12\x11\n\tbitstring\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x86\x01\n\x12RunCircuitResponse\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12.\n\x0c\x64istribution\x18\x04 \x03(\x0b\x32\x18.hwman.DistributionEntry\x12\x11\n\tdata_path\x18\x05 \x01(\t2M\n\x08\x43ircuits\x12\x41\n\nRunCircuit\x12\x18.hwman.RunCircuitRequest\x1a\x19.hwman.RunCircuitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hwman.grpc.protobufs.circuits_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATE']._serialized_start=46
  _globals['_GATE']._serialized_end=131
  _globals['_RUNCIRCUITREQUEST']._serialized_start=133
  _globals['_RUNCIRCUITREQUEST']._serialized_end=208
  _globals['_DISTRIBUTIONENTRY']._serialized_start=210
  _globals['_DISTRIBUTIONENTRY']._serialized_end=263
  _globals['_RUNCIRCUITRESPONSE']._serialized_start=266
  _globals['_RUNCIRCUITRESPONSE']._serialized_end=400
  _globals['_CIRCUITS']._serialized_start=402
  _globals['_CIRCUITS']._serialized_end=479
# @@protoc_insertion_point(module_scope)
