# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hwman/grpc/protobufs/jobs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hwman/grpc/protobufs/jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hwman.grpc.protobufs_compiled import users_pb2 as hwman_dot_grpc_dot_protobufs_dot_users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fhwman/grpc/protobufs/jobs.proto\x1a hwman/grpc/protobufs/users.proto\"!\n\nJobPayload\x12\x13\n\x0bplaceholder\x18\x63 \x01(\t\"<\n\x08\x44\x61taAxis\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x12\n\ndepends_on\x18\x03 \x03(\t\";\n\x06Result\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\t.DataAxis\x12\x0c\n\x04path\x18\x03 \x01(\t\"\x91\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x04user\x18\x02 \x01(\x0b\x32\x05.User\x12\x16\n\x04type\x18\x03 \x01(\x0e\x32\x08.JobType\x12\x1a\n\x06status\x18\x04 \x01(\x0e\x32\n.JobStatus\x12\x1c\n\x07payload\x18\x05 \x01(\x0b\x32\x0b.JobPayload\x12\x17\n\x06result\x18\x06 \x01(\x0b\x32\x07.Result*v\n\x07JobType\x12\x18\n\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10JOB_TYPE_CONTROL\x10\x01\x12\x14\n\x10JOB_TYPE_CIRCUIT\x10\x02\x12\x11\n\rJOB_TYPE_TEST\x10\x03\x12\x12\n\x0eJOB_TYPE_DUMMY\x10\x04*o\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n\x12JOB_STATUS_SUCCESS\x10\x02\x12\x16\n\x12JOB_STATUS_FAILURE\x10\x03\x32&\n\x0bJobDispatch\x12\x17\n\tSubmitJob\x12\x04.Job\x1a\x04.Jobb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hwman.grpc.protobufs.jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBTYPE']._serialized_start=375
  _globals['_JOBTYPE']._serialized_end=493
  _globals['_JOBSTATUS']._serialized_start=495
  _globals['_JOBSTATUS']._serialized_end=606
  _globals['_JOBPAYLOAD']._serialized_start=69
  _globals['_JOBPAYLOAD']._serialized_end=102
  _globals['_DATAAXIS']._serialized_start=104
  _globals['_DATAAXIS']._serialized_end=164
  _globals['_RESULT']._serialized_start=166
  _globals['_RESULT']._serialized_end=225
  _globals['_JOB']._serialized_start=228
  _globals['_JOB']._serialized_end=373
  _globals['_JOBDISPATCH']._serialized_start=608
  _globals['_JOBDISPATCH']._serialized_end=646
# @@protoc_insertion_point(module_scope)
