# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hwman/grpc/protobufs/test.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'hwman/grpc/protobufs/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fhwman/grpc/protobufs/test.proto\":\n\x0c\x46itParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\r\n\x05\x65rror\x18\x03 \x01(\x01\"a\n\x0bTestRequest\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x1c\n\ttest_type\x18\x02 \x01(\x0e\x32\t.TestType\x12\r\n\x05shots\x18\x03 \x01(\x05\x12\x18\n\x10return_full_data\x18\x04 \x01(\x08\"\xca\x01\n\x0cTestResponse\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x11\n\tdata_path\x18\x03 \x01(\t\x12\x0b\n\x03snr\x18\x04 \x01(\x01\x12\x38\n\x0e\x66it_parameters\x18\x05 \x03(\x0b\x32 .TestResponse.FitParametersEntry\x1a\x43\n\x12\x46itParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.FitParameter:\x02\x38\x01*\xc3\x01\n\x08TestType\x12\x1b\n\x17\x41\x44\x43_TRIGGER_CALIBRATION\x10\x00\x12\x12\n\x0eRESONATOR_SPEC\x10\x01\x12\x1c\n\x18PULSE_PROBE_SPECTROSCOPY\x10\x02\x12\x0e\n\nPOWER_RABI\x10\x03\x12\x0b\n\x07PI_SPEC\x10\x04\x12\x1b\n\x17RESONATOR_SPEC_AFTER_PI\x10\x05\x12\x06\n\x02T1\x10\x06\x12\x07\n\x03T2R\x10\x07\x12\x07\n\x03T2E\x10\x08\x12\x14\n\x10STATE_ASSIGNMENT\x10\t2\xf7\x03\n\x04Test\x12+\n\x0cStandardTest\x12\x0c.TestRequest\x1a\r.TestResponse\x12)\n\nResSpecCal\x12\x0c.TestRequest\x1a\r.TestResponse\x12/\n\x10ResSpecVsGainCal\x12\x0c.TestRequest\x1a\r.TestResponse\x12&\n\x07SatSpec\x12\x0c.TestRequest\x1a\r.TestResponse\x12(\n\tPowerRabi\x12\x0c.TestRequest\x1a\r.TestResponse\x12%\n\x06PiSpec\x12\x0c.TestRequest\x1a\r.TestResponse\x12-\n\x0eResSpecAfterPi\x12\x0c.TestRequest\x1a\r.TestResponse\x12!\n\x02T1\x12\x0c.TestRequest\x1a\r.TestResponse\x12\"\n\x03T2R\x12\x0c.TestRequest\x1a\r.TestResponse\x12\"\n\x03T2E\x12\x0c.TestRequest\x1a\r.TestResponse\x12$\n\x05ROCal\x12\x0c.TestRequest\x1a\r.TestResponse\x12-\n\x0eTuneUpProtocol\x12\x0c.TestRequest\x1a\r.TestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hwman.grpc.protobufs.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTRESPONSE_FITPARAMETERSENTRY']._loaded_options = None
  _globals['_TESTRESPONSE_FITPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TESTTYPE']._serialized_start=400
  _globals['_TESTTYPE']._serialized_end=595
  _globals['_FITPARAMETER']._serialized_start=35
  _globals['_FITPARAMETER']._serialized_end=93
  _globals['_TESTREQUEST']._serialized_start=95
  _globals['_TESTREQUEST']._serialized_end=192
  _globals['_TESTRESPONSE']._serialized_start=195
  _globals['_TESTRESPONSE']._serialized_end=397
  _globals['_TESTRESPONSE_FITPARAMETERSENTRY']._serialized_start=330
  _globals['_TESTRESPONSE_FITPARAMETERSENTRY']._serialized_end=397
  _globals['_TEST']._serialized_start=598
  _globals['_TEST']._serialized_end=1101
# @@protoc_insertion_point(module_scope)
