instruments:
  dummy_instrument_random_number:
    type: instrumentserver.testing.dummy_instruments.generic.DummyInstrumentRandomNumber
    initialize: True
  parameter_manager2:
    type: instrumentserver.params.ParameterManager
    initialize: True
    gui:
      type: instrumentserver.gui.instruments.ParameterManagerGui
