#name: Code quality
#on:
#  pull_request:
#    types: [opened, synchronize, reopened]
#permissions:
#  contents: read
#jobs:
#  lockfile:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: astral-sh/setup-uv@v4
#      - run: uv lock --locked
#  lint:
#    runs-on: ubuntu-latest
#    needs: [lockfile]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: astral-sh/setup-uv@v4
#      - run: uv run ruff check
#  format:
#    runs-on: ubuntu-latest
#    needs: [lockfile]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: astral-sh/setup-uv@v4
#      - run: uv run ruff format --check
#  typecheck:
#    runs-on: ubuntu-latest
#    needs: [lockfile]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: astral-sh/setup-uv@v4
#      - run: uv run mypy hwman
